#!/usr/bin/python3

if __name__ == "__main__":
    """performs some basic calculation"""
from calculator_1 import add, sub, mul, div
import sys
if (len(sys.argv) != 3):
    print("Usage: ./100-my_calculator.py <a> <operator> <b>")
    exit(1)
if ((sys.argv[1] != '+') or (sys.argv[1] != '-') or (sys.argv[1] != '*') or (sys.argv[1] != '/')):
    print("Unknown operator. Available operators: +, -, * and /")
a = int(sys.argv[0])
b = int(sys.argv[2])
operator = sys.argv[1]
if operator == '+':
    result = add(a, b)
elif operator == '-':
    result = sub(a, b)
elif operator == '*':
    result = mul(a, b)
elif operator == '/':
    result = div(a, b)
print("{} {} {} = {}".format(a, operator, b, result))
